[base]
mode = "workspace"
smart_pull = true

[mode.workspace]
git_info = true
colorblind = true

[repositories]
repos = [
  # My programs
  "nms:pronounce",
  "tar:parse",
  "alchemi:caveman",
  
  # Ad Astra
  "ada:homeserve",
  "afs:build-system",
  "afs:mixiek-route",
  
  # Misc
  "nms:flake",
  "qmk:qmk_firmware:1",
  
  # My forks
  "nms:sshs",
]

[repositories.urls]
ada = "ssh://git@git.tar.black/ad-astra/{}"
afs = "ssh://git@git.tar.black/ad-astra/friendsim/{}"
alchemi = "ssh://git@github.com/Codealchemi/{}"
nms = "ssh://git@github.com/not-my-segfault/{}"
qmk = "ssh://git@github.com/qmk/{}"
tar = "ssh://gitea@git.tar.black/michal/{}"
